version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market
    volumes:
      - ./db/init/01_create_extensions.sql:/docker-entrypoint-initdb.d/01_create_extensions.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  market_data:
    build: ../services/market_data
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/market
      REDIS_URL: redis://redis:6379/0
      TZ: UTC
    ports:
      - "8001:8000"
    depends_on:
      - db

  rag:
    build: ../services/rag
    ports:
      - "8002:8000"
    depends_on:
      - db

  llm:
    build: ../services/llm
    ports:
      - "8003:8000"
    depends_on:
      - db

  gateway:
    build: ../gateway
    ports:
      - "8000:8000"
    depends_on:
      - market_data
      - rag
      - llm
